Posts/urls.py
from django.urls import path
from .views import (post_list_view, PostDetailView, post_create_view, post_draft_list_view, PostDraftDetailView,
                    publish_post, PostDeleteView, PostEditView)

app_name = 'Posts'

urlpatterns = [
    path('list/', post_list_view, name='post_list'),
    path('draft_list/', post_draft_list_view, name='post_draft_list'),
    path('create/', post_create_view, name='post_create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('draft/<slug:slug>/', PostDraftDetailView.as_view(), name='post_draft_detail'),
    path('publish/<slug:slug>', publish_post, name='post_publish'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<slug:slug>', PostEditView.as_view(), name='post_edit')
]

ZielonoNam/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
import ZielonoNam.views as main_views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.IndexView.as_view(), name='index'),
    path('contact/', main_views.ContactView.as_view(), name='contact'),

    path('user/', include('accounts.urls')),
    path('posts/', include('Posts.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_PATH)

accounts/urls.py
from unicodedata import name
from django.urls import path, reverse_lazy
from .views import UserLoginView, LogOutView, user_register_view, change_password_view
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('register/', user_register_view, name='register'),
    path('change_password/', change_password_view, name='pass_change'),

    # Password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done'), form_class=UserPasswordResetForm),
         name='password_reset'),

    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Posts/models.py
from django.db import models
from django.utils.text import slugify
from accounts.models import User
import datetime
from tinymce.models import HTMLField


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250, blank=False, null=False, unique=True)
    content = HTMLField()
  #  thumbnail = models.ImageField(upload_to='thumbnails')
    cdn_url = models.CharField(max_length=350)
    slug = models.SlugField(null=True, blank=True)
    create_date = models.DateField(auto_now_add=True)
    publish_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title)
        else:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.publish_date = datetime.datetime.now()
        self.save()

Posts/forms.py
from django import forms
from .models import Post
from tinymce.widgets import TinyMCE


class PostCreateForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'class': 'form_inp', 'placeholder': 'Tytuł'}), label="")
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}), label="")
    thumbnail = forms.ImageField()

    class Meta:
        model = Post
        fields = ('title', 'content', )

Posts/views.py
from django.shortcuts import render
from django.views.generic import DetailView, TemplateView, DeleteView, UpdateView
from django.core.paginator import Paginator
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import reverse
from .forms import PostCreateForm
from django.urls import reverse_lazy
from django.contrib import messages
import random

# Importing config variables for FireBase
from ZielonoNam.settings import THUMBNAILS_DIR, storage


def post_list_view(request):
    """Published posts list view"""
    post_list = Post.objects.filter(publish_date__isnull=False).order_by('-publish_date')

    paginator = Paginator(post_list, 1)
    page_number = request.GET.get('page')
    post = paginator.get_page(page_number)

    return render(request, 'posts/posts.html', {'page_obj': post})


@user_passes_test(lambda u: u.is_superuser)
@login_required()
def post_draft_list_view(request):
    """Unpublished posts list view"""
    post_draft_list = Post.objects.filter(publish_date__isnull=True).order_by('-create_date')

    paginator = Paginator(post_draft_list, 1)
    page_number = request.GET.get('page')
    post_draft = paginator.get_page(page_number)

    return render(request, 'posts/posts.html', {'page_obj': post_draft})


class PostDetailView(DetailView):
    """Published post DetailView"""
    model = Post
    template_name = 'posts/post_detail.html'

    def get_queryset(self):
        queryset = super(PostDetailView, self).get_queryset()
        return queryset.filter(publish_date__isnull=False)


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class PostDraftDetailView(DetailView, LoginRequiredMixin):
    """Unpublished post DetailView"""
    login_url = '/user/login/'
    model = Post
    template_name = 'posts/post_detail.html'

    def get_queryset(self):
        queryset = super(PostDraftDetailView, self).get_queryset()
        return queryset.filter(publish_date__isnull=True)


@user_passes_test(lambda u: u.is_superuser)
@login_required
def publish_post(request, slug):
    """Publishing post"""
    post = Post.objects.get(slug=slug)

    post.publish()
    return HttpResponseRedirect(reverse('Posts:post_list'))


@user_passes_test(lambda u: u.is_superuser)
@login_required()
def post_create_view(request):
    """Post creation view"""
    form = PostCreateForm()
    if request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.author = request.user
            file = form.cleaned_data['thumbnail']
            form.save()
            post = Post.objects.get(title=form.instance.title)
            n = random.randint(2150, 195213)
            storage.child(THUMBNAILS_DIR + f'{n}_{file.name}').put(file)
            post.cdn_url = storage.child(THUMBNAILS_DIR + f'{n}_{file.name}').get_url(None)
            print(post.cdn_url)
            post.save()
            return HttpResponseRedirect(reverse('Posts:post_draft_list'))
        else:
            messages.info(request, form.errors)
            return render(request, 'posts/post_add.html', {'form': form})
    else:
        return render(request, 'posts/post_add.html', {'form': form})


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class PostDeleteView(DeleteView, LoginRequiredMixin):
    login_url = '/user/login/'
    model = Post
    success_url = reverse_lazy('Posts:post_list')
    template_name = 'posts/post_confirm_delete.html'


@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class PostEditView(UpdateView, LoginRequiredMixin):
    login_url = '/user/login/'
    model = Post
    fields = ['title', 'content']
    template_name = 'posts/post_add.html'
    success_url = reverse_lazy('Posts:post_list')

templates/posts/post_add.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/post_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="{% url 'Posts:post_list' %}">
              Posty
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'contact' %}">
                Kontakt
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
          <h1>Dodaj post</h1>
           {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
      </div>
      <main>
        <div class="post_cont" style="text-align: center">
            <form method="post" enctype="multipart/form-data" autocomplete="off">
                {{ form.as_p }}
                {{ form.media }}
                {% csrf_token %}
                <button id='btn' type="submit">Zapisz</button>
            </form>
        </div>
          <style>
              label{
                  flex-direction: column;
                  text-align: center;
              }
              input[type=text]{
                  margin-bottom: 30px;
              }
          </style>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/posts/post_confirm_delete.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/post_detail.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="{% url 'Posts:post_list' %}">
              Posty
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'contact' %}">
                Kontakt
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
      </div>
      <main>
        <div class="post_cont" >
            <h1 style="text-align: center">Napewno chcesz usunąc post: <strong>{{ post.title }}</strong>?</h1>
            <form method="POST" style="text-align: center">
                {% csrf_token %}
                <button id='btn' type="submit" style="color: Red">Tak</button>
                <button id="btn"><a href="{% url 'Posts:post_detail' post.slug %}">Nie</a></button>
            </form>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/posts/post_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/post_detail.css' %}">
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="{% url 'Posts:post_list' %}">
              Posty
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'contact' %}">
                Kontakt
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
      </div>
      <main>
        <div class="post_cont" >
            <h2 id="tittle">{{ post.title }} {% if not post.publish_date%}<a href="{% url 'Posts:post_publish' slug=post.slug %}">[Opublikuj]</a>{% endif %} </h2>
            <span style="font-size: 35px">{% if user.is_authenticated %}<a href="{% url 'Posts:post_delete' post.slug %}"><i class="fas fa-trash-alt"></i></a><a href="{% url 'Posts:post_edit' post.slug %}"><i class="fa-solid fa-pen"></i></a>{% endif %}</span>
            <h2>Autor: <a href="#">{{ post.author }}</a></h2>
            <h2>Napisane: {{ post.create_date }}</h2>
            <hr>
            <div id="post_text">
                <p>{{ post.content|safe }}</p>
            </div>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/posts/posts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">]
    <link rel="stylesheet" href="{% static 'css/posts.css' %}" type="text/css">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'contact' %}">
                Kontakt
              </a>
            {% if not user.is_authenticated %}
            <a class="navbar-item" href="{% url 'accounts:login' %}">
                Login
              </a>
            {% endif %}
              {% if user.is_superuser %}
            <a class="navbar-item" href="{% url 'Posts:post_create' %}">
                Dodaj post
              </a>
            <a class="navbar-item" href="{% url 'Posts:post_draft_list' %}">Nieopublikowane</a>
              {% endif %}
          </div>
        </div>
      </nav>
          <div id="main_header">
      </div>
      <main>
      <span>{% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-angle-double-left mob_arr"></i></a> {% endif %} {% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-angle-double-right mob_arr"></i></a>{% endif %}</span>
        <div class='main_cont'>
            {% if not page_obj %}
            <h1 style="font-size: 45px;">Brak postów!</h1>
        {% endif %}
          <div class="arrow_div" id="back_div">{% if page_obj.has_previous %}<a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-angle-double-left"></i></a>{% endif %}</div>
        {% for post in page_obj  %}
          <div class="post_div">
            <div class="post_cont">
              <div class="image_div">
                <img src="{{ post.cdn_url }}" class="post_image">
              </div>
              <div class="post_content">
                <span><h1 class="post_title">{{ post.title }}</h1><p class="post_date">{{ post.publish_date }}</p></span>
                <a class="post_author">{{post.author.username}}</a>
              <hr>
              <span>
              {% if post.publish_date %}
                  <a href="{% url 'Posts:post_detail' slug=post.slug %}">Kliknij po więcej</a>{% else %}
                  <a href="{% url 'Posts:post_draft_detail' slug=post.slug %}">Kliknij po więcej</a>
                {% endif %}
              </span>
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="arrow_div" id="next_div">{% if page_obj.has_next %}<a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-angle-double-right"></i></a>{% endif %}</div>
        </div>
      </main>
</body>
{% if not page_obj %}
    <style>
        body{
            height: 100vh !important;
        }
    </style>
{% endif %}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>