Posts/urls.py
from django.urls import path
from .views import (post_list_view, PostDetailView, post_create_view, post_draft_list_view, PostDraftDetailView,
                    publish_post, PostDeleteView, PostEditView)

app_name = 'Posts'

urlpatterns = [
    path('list/', post_list_view, name='post_list'),
    path('draft_list/', post_draft_list_view, name='post_draft_list'),
    path('create/', post_create_view, name='post_create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('draft/<slug:slug>/', PostDraftDetailView.as_view(), name='post_draft_detail'),
    path('publish/<slug:slug>', publish_post, name='post_publish'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<slug:slug>', PostEditView.as_view(), name='post_edit')
]

ZielonoNam/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
import ZielonoNam.views as main_views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.IndexView.as_view(), name='index'),
    path('contact/', main_views.ContactView.as_view(), name='contact'),

    path('user/', include('accounts.urls')),
    path('posts/', include('Posts.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_PATH)

accounts/urls.py
from unicodedata import name
from django.urls import path, reverse_lazy
from .views import UserLoginView, LogOutView, user_register_view, change_password_view
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

app_name = 'accounts'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('register/', user_register_view, name='register'),
    path('change_password/', change_password_view, name='pass_change'),

    # Password reset views
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done'), form_class=UserPasswordResetForm),
         name='password_reset'),

    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("accounts:password_reset_complete")), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

Accounts/models.py
from distutils.command.upload import upload
from importlib.metadata import requires
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=250, unique=True)
    profile_pic = models.ImageField(upload_to='profile_pics')

    def __str__(self) -> str:
        return self.username

accounts/models.py
from distutils.command.upload import upload
from importlib.metadata import requires
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=250, unique=True)
    profile_pic = models.ImageField(upload_to='profile_pics')
    pp_cdn_url = models.CharField(max_length=350)

    def __str__(self) -> str:
        return self.username

accounts/forms.py
from django.contrib.auth.forms import PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.password_validation import validate_password
from django import forms
from .models import User


class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form_inp', 'placeholder': 'Nazwa użytkownika'}), label='')
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form_inp', 'placeholder': 'Email'}), label='')
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp', 'placeholder': 'Hasło'}), label='')
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp', 'placeholder': 'Potwierdź Hasło'}), label='')
    profile_pic = forms.ImageField(label='Zdjęcie profilowe', widget=forms.FileInput(attrs={'class': 'img_fld'}))

    def clean(self):
        cleaned_data = super(UserRegisterForm, self).clean()
        password = cleaned_data['password']
        confirm_password = cleaned_data['confirm_password']

        if password != confirm_password:
            raise forms.ValidationError(
                "Hasła się różnią"
            )

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'profile_pic',)
    
    field_order = ['username', 'email', 'password', 'confirm_password', 'profile_pic']
        

class UserChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserChangePasswordForm, self).__init__(*args, **kwargs)

    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp', 'placeholder': 'Stare hasło'}), label='')
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp', 'placeholder': 'Nowe hasło'}), label='')
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp', 'placeholder': 'Powtórz stare hasło'}), label='')


class UserSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(UserSetPasswordForm, self).__init__(*args, **kwargs)

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp'}),
                               validators=[validate_password], label='')
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form_inp'}), label='')

    #   Cleaning data to get password input and check if passwords match
    def clean(self):
        cleaned_data = super(UserSetPasswordForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Passwords do not match"
            )


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'class': 'form_inp'}))

Accounts/views.py
import re
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import UserRegisterForm, UserChangePasswordForm


class UserLoginView(View):
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(password)
        user = authenticate(request=request ,username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request=request, user=user)
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.error(request, "Użytkownik nieaktywny")
                return render(request, 'accounts/login.html')
        else:
            messages.error(request, "Złe hasło lub nazwa użytkownika")
            return render(request, 'accounts/login.html', {})


    def get(self, request):
        return render(request, 'accounts/login.html', {})


class LogOutView(View, LoginRequiredMixin):
    login_url = '/user/login'

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


def user_register_view(request):
    user_form = UserRegisterForm()

    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            return HttpResponseRedirect(reverse('accounts:login'))
        else:
            messages.info(request, user_form.errors)

    return render(request, 'accounts/register.html', {'form': user_form})


@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = UserChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return HttpResponseRedirect(reverse('accounts:login')) 
        else:
            messages.info(request, form.errors)
    else:
        form = UserChangePasswordForm(request.user)

    return render(request, 'accounts/change_password.html', {'form': form})

accounts/views.py
import re
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.contrib import messages
from .forms import UserRegisterForm, UserChangePasswordForm
from .models import User
from ZielonoNam.settings import PROFILE_PICS_DIR, storage
from django.utils.text import slugify


class UserLoginView(View):
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request=request ,username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request=request, user=user)
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.error(request, "Użytkownik nieaktywny")
                return render(request, 'accounts/login.html')
        else:
            messages.error(request, "Złe hasło lub nazwa użytkownika")
            return render(request, 'accounts/login.html', {})

    def get(self, request):
        return render(request, 'accounts/login.html', {})


class LogOutView(View, LoginRequiredMixin):
    login_url = '/user/login'

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


def user_register_view(request):
    user_form = UserRegisterForm

    if request.method == 'POST':
        user_form = UserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            user_obj = User.objects.get(username=user_form.instance.username)
            file = user_obj.profile_pic
            storage.child(file.name).put("media/" + file.name)
            user_obj.pp_cdn_url = storage.child(file.name).get_url(None)
            user_obj.save()
            return HttpResponseRedirect(reverse('accounts:login'))
        else:
            messages.info(request, user_form.errors)

    return render(request, 'accounts/register.html', {'form': user_form})


@login_required
def change_password_view(request):
    if request.method == 'POST':
        form = UserChangePasswordForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            return HttpResponseRedirect(reverse('accounts:login')) 
        else:
            messages.info(request, form.errors)
    else:
        form = UserChangePasswordForm(request.user)

    return render(request, 'accounts/change_password.html', {'form': form})

templates/accounts/change_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="index.html">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="">
                Posty
              </a>
            <a class="navbar-item" href="newsletter.html">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1></h1>
      </div>
      <main>
        <div class="" id='login_cont'>
            <h2>ADMIN</h2>
            <span><a id="inactive">Zaloguj się</a><a href='register.html' id="active">Zarejestruj się</a></span>
            <form method="POST">
                {{form}}
                {% csrf_token %}
                <button id='btn' type="submit">Zmień hasło</button>
            </form>
            
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/accounts/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="">
                Posty
              </a>
            <a class="navbar-item" href="">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1></h1>
      </div>
      <main>
        <div class="" id='login_cont'>
            <h2>ADMIN</h2>
            
            <span><a id="inactive">Zaloguj się</a><a href='{% url 'accounts:register' %}' id="active">Zarejestruj się</a></span><br>
            <a href="{% url 'accounts:password_reset' %}">Zresetuj hasło</a>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method="POST" enctype="multipart/form-data" autocomplete="off">
              <input id='username' name="username" class='form_inp' type="text" placeholder="Nazwa użytkownika">
              <br>
              <input id='password' name='password' class='form_inp' type="password" placeholder="Hasło">
              <br>
              <button id='btn' type="submit">Zaloguj się</button>
              {% csrf_token %}
            </form>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/accounts/password_reset_confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico"' %}/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="">
                Posty
              </a>
            <a class="navbar-item" href="">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1></h1>
      </div>
      <main>
        <div class="" id='login_cont'>
            <h2 id="login_header">Potwierdź zmiane hasła</h2>
            <h3>Podaj nowe hasło</h3>
            <form method="POST">
                {{ form }}
                {% csrf_token %}
              <button id='btn' type="submit">Zresetuj</button>
            </form>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/accounts/password_reset_done.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico"' %}/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="">
                Posty
              </a>
            <a class="navbar-item" href="">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1></h1>
      </div>
      <main>
        <div class="" id='login_cont'>
            <h2 id="login_header">Kontynuuj resetowanie hasła</h2>
            <p>Jeżeli konto istnieje, na podany email wysłaliśmy instukcje resetu.</p>
            <h3></h3>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>

templates/accounts/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="index.html">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="">
                Posty
              </a>
            <a class="navbar-item" href="newsletter.html">
                Newsletter
              </a>s
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1></h1>
      </div>
      <main>
        <div class="" id='login_cont' style="height: 450px">
            <h2>ADMIN</h2>
            <span><a href="{% url 'accounts:login' %}" id="active">Zaloguj się</a><a id="inactive">Zarejestruj się</a></span>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method="POST" enctype="multipart/form-data" autocomplete="off">
              {{form.as_p}}
              {% csrf_token %}
              <button id='btn' type="submit">Zarejestruj się</button>
            </form>
        </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
</html>