Posts/urls.py
from django.urls import path
from .views import (post_list_view, PostDetailView, post_create_view, post_draft_list_view, PostDraftDetailView,
                    publish_post, PostDeleteView, PostEditView)

app_name = 'Posts'

urlpatterns = [
    path('list/', post_list_view, name='post_list'),
    path('draft_list/', post_draft_list_view, name='post_draft_list'),
    path('create/', post_create_view, name='post_create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('draft/<slug:slug>/', PostDraftDetailView.as_view(), name='post_draft_detail'),
    path('publish/<slug:slug>', publish_post, name='post_publish'),
    path('delete/<slug:slug>', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<slug:slug>', PostEditView.as_view(), name='post_edit')
]

ZielonoNam/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, include
import ZielonoNam.views as main_views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.IndexView.as_view(), name='index'),
    path('contact/', main_views.ContactView.as_view(), name='contact'),

    path('user/', include('accounts.urls')),
    path('posts/', include('Posts.urls'))
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_PATH)

templates/contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <script src="https://kit.fontawesome.com/88dec51e8e.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'index' %}">
              Home
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'Posts:post_list' %}">
                Posty
              </a>
            <a class="navbar-item" href="">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1>Kontakt</h1>
      </div>
      <main>
        <div id="contact_div">
                <div id="cont_2">
                    <div id='social_links'>
                        <div class="social_link">
                            <i class="fab fa-instagram"></i>
                            <h2 class="social_link"> <a href="https://www.instagram.com/zielononam2022/" target="_blank">@zielononam2022</a></h2>
                        </div>
                        <div class="social_link">
                            <i class="fab fa-facebook"></i>
                            <h2 class="social_link"> <a href=" https://www.facebook.com/profile.php?id=100077325723288" target="_blank">Zielono Nam</a></h2>
                        </div>
                        <div class="social_link">
                            <i class="fas fa-inbox"></i>
                            <h2 class="social_link"> <a href="mailto:zielononam@gmail.com">zielononam@gmail.com</a></h2>
                        </div>
                    </div>
                    <div id="ilustration_div">
                        <img src="{% static 'images/hipster-man-with-social-media (1).png' %}" width="400px">
                    </div>
                </div>
        </div>
      </main>
</body>
<script src="{% static 'js/burger.js' %}"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
</html>

templates/index.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/icon" href="{% static 'images/icon2.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <title>ZielonoNam 2022</title>
</head>
<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" id="logo">
          <a role="button" class="navbar-burger is_large" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start" >
            <a class="navbar-item" href="{% url 'Posts:post_list' %}">
              Posty
            </a>
            <a class="navbar-item" href="">
              O nas
            </a>
            <a class="navbar-item" href="{% url 'contact' %}">
                Kontakt
              </a>
            <a class="navbar-item" href="">
                Newsletter
              </a>
          </div>
        </div>
      </nav>
      <div id="main_header">
        <h1>Zielono Nam 2022</h1>
      </div>
      <main>
        <div class="container" style="padding-top:15px; padding-left: 15px; padding-right: 15px;">
          <img src="{% static 'images/hat.png' %}" style="margin-bottom: 110px;">
          <div class='text_div' style="border-top:2px solid black;">
            <p>Zielono Nam to projekt, który zagłębi Was w tematykę legalizacji marihuany w Polsce. Omówimy pozytywne, jak i negatywne skutki tego przedsięwzięcia. Posłuchamy opinii obywateli co sądzą na ten temat i wysuniemy wnioski. A Ty jesteś na tak z legalizacją marihuany?</p>
          </div>
        </div>
        <div  class="container">
            <img src="{% static 'images/magnifier.png' %}" width="250px" style="margin-top: 5px;">
            <div class='text_div' style="border-top:2px solid black;">
              <p>Przyjrzymy się problemowi społecznemu związanemu z dostępnością legalnej marihuany w Polsce. Przedstawimy
                  negatywne jak i pozytywne skutki zażywania Konopii. Zastanowimy się również nad korzyściami płynącymi
                  z legalizacjia - dla państwa.
              </p>
            </div>
        </div>
        <div  class="container">
          <img src="{% static 'images/board.png' %}" style="margin-left: 20px; margin-top: 20px;">
          <div class='text_div' style="border-top:2px solid black;">
            <p>Postaramy się dostarczyć sprawdzoną i ciekawą wiedzę na temat konopii. Informacje przekazywane są w formie krótkich ciekawostek na naszym
            Instagramie oraz w formie dłuższych postów na naszej stronie. </p>
          </div>
      </main>
</body>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-BMRFLSCRNQ"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-BMRFLSCRNQ');
</script>
<script src="{% static 'js/burger.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vanilla-tilt/1.7.2/vanilla-tilt.min.js" integrity="sha512-K9tDZvc8nQXR1DMuT97sct9f40dilGp97vx7EXjswJA+/mKqJZ8vcZLifZDP+9t08osMLuiIjd4jZ0SM011Q+w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</html>